# Generated by Django 3.1.3 on 2020-11-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
