# Generated by Django 3.1.3 on 2020-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problematic_relation', '0002_auto_20201119_1757'),
        ('m2m', '0002_auto_20201119_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='problematic_relation.StudentSubject', to='problematic_relation.Subject'),
        ),
    ]
