# Generated by Django 3.1.3 on 2020-11-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('study', 'study'), ('none_study', 'none_study')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mbalisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subjects', models.ManyToManyField(through='problematic_relation.ClassSubject', to='problematic_relation.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='classsubject',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problematic_relation.studentclass'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problematic_relation.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to='problematic_relation.mbalisi'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('klass', 'subject')},
        ),
    ]
