# Generated by Django 3.1.3 on 2020-11-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0002_auto_20201119_1614'),
        ('problematic_relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'ENROLLED'), ('disenroll', 'DISENROLLED')], default='enrolled', max_length=200)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('enr_klass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problematic_relation.studentclass')),
                ('stdnt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='m2m.student')),
            ],
            options={
                'unique_together': {('stdnt', 'enr_klass')},
            },
        ),
        migrations.AddField(
            model_name='studentclass',
            name='students',
            field=models.ManyToManyField(through='problematic_relation.StudentEnrollment', to='m2m.Student'),
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('study', 'study'), ('none_study', 'none_study')], max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='m2m.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problematic_relation.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
