# Generated by Django 3.1.3 on 2020-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('number', models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='0DE63A957312468E8CFF')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
    ]
