# Generated by Django 3.1.3 on 2020-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiiding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='BEFFAB2F98354D3AAA38'),
        ),
    ]
