# Generated by Django 3.1.3 on 2020-11-18 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uiiding', '0002_auto_20201118_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='7B21A3F6A4304474A98E'),
        ),
    ]
