# Generated by Django 3.1.3 on 2020-11-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiiding', '0004_auto_20201118_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='number',
            field=models.UUIDField(default='4D5AE3A367D74C78B8E1', editable=False, primary_key=True, serialize=False),
        ),
    ]
