# Generated by Django 3.1.3 on 2020-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiiding', '0005_auto_20201118_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='number',
            field=models.CharField(blank=True, default='434D31DB8D', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
