# Generated by Django 3.1.3 on 2020-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiiding', '0006_auto_20201118_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='number',
            field=models.CharField(blank=True, default='A652DD1F1A', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
