# Generated by Django 3.1.3 on 2020-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiiding', '0010_auto_20201119_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='number',
            field=models.CharField(blank=True, default='5363C6ADFE', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
