# Generated by Django 3.1.3 on 2020-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiiding', '0014_auto_20201119_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='number',
            field=models.CharField(blank=True, default='CF4DF7C31D', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
